# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    # specify the version you desire here
    - image: circleci/node:7.10

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/mongo:3.4.4

    working_directory: ~/ecommerce-api

    steps:
    - checkout

    # Download and cache dependencies
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-

    - run: npm install

    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}

    # run test!
    - run: npm test

  deploy:
    machine:
      enabled: true
    working_directory: ~/ecommerce-api
    master:
      branch: staging
    steps:
      - run:
          name: SSH into the server
          command: ssh root@67.205.169.51 "cd ~/ecommerce-api;./circle_deployer.sh"
      - run:
          name: Change Directory into the Project
          command: cd /root/work
      - run:
          name: Pull changes from the repository
          command: git pull origin staging
      - run:
          name: Run NPM install
          command: npm install
      - run:
          name: Restart PM2
          command: pm2 restart all